#!/bin/sh

tmpfile="$(mktemp -p /tmp nekofetchXXXXXXXX)"

case "$1" in
    "--nsfw"|"nsfw"|"-n"|"n")
        echo "Getting a nsfw image"
        imgurl="https://nekos.life/api/v2/img/cum_jpg"
        ;;
    "--sfw"|"sfw"|"-s"|"s")
        echo "Getting a sfw image"
        imgurl="https://nekos.life/api/v2/img/neko"
        ;;
    *)
        echo "Could not interpret as either sfw or nsfw. Defaulting to sfw."
        imgurl="https://nekos.life/api/v2/img/neko"
        ;;
esac

url=$(curl -fsSL "$imgurl" | jq -r ".url")

curl -fsSLo "$tmpfile.jpg" "$url"
if [ "$TERM" = "xterm-kitty" ]; then
    neofetch --kitty "$tmpfile.jpg"
else
    clear
    neofetch --jp2a "$tmpfile.jpg"  --crop_mode fill
fi

rm "$tmpfile.jpg"
