#!/bin/sh

tmpfile="$(mktemp)"
imgurl="https://nekos.life/api/v2/img/neko"
height="$(($(stty size | awk '{print $1}') - 5))"

while :; do
    case "$1" in
        "--nsfw"|"nsfw"|"-n"|"n")
            [ "$DEBUG" = "true" ] && echo "Getting a nsfw image"
            imgurl="https://nekos.life/api/v2/img/cum_jpg"
            ;;
        "--sfw"|"sfw"|"-s"|"s")
            [ "$DEBUG" = "true" ] && echo "Getting a sfw image"
            imgurl="https://nekos.life/api/v2/img/neko"
            ;;
        "--w3m"|"w3m"|"--img"|"img"|"-i"|"i")
            [ "$DEBUG" = "true" ] && echo "Using w3m image backend for neofetch"
            use_w3m="true"
            ;;
        "--height"|"-h")
            height="$2"
            [ "$DEBUG" = "true" ] && echo "Using height $height"
            shift
            ;;
        *)
            if [ -z "$1" ]; then
                break
            fi
            [ "$DEBUG" = "true" ] && echo "Could not interpret parameter '$1'."
            ;;
    esac
    shift
done

url=$(curl -fsSL "$imgurl" | jq -r ".url")

curl -fsSLo "$tmpfile.jpg" "$url"
if [ "$TERM" = "xterm-kitty" ]; then
    command -v convert > /dev/null 2>&1 && neofetch --kitty "$tmpfile.jpg" || kitty_imagemagick_warn=true
    if [ "$kitty_imagemagick_warn" = "true" ]; then
        jp2a --height="$height" "$tmpfile.jpg" > "$tmpfile"
        neofetch --source "$tmpfile"
    fi
elif [ "$LC_TERMINAL" = "iTerm2" ]; then
    neofetch --iterm2 "$tmpfile.jpg"
elif [ "$use_w3m" = "true" ]; then
    neofetch --w3m "$tmpfile.jpg"
else
    jp2a --height="$height" "$tmpfile.jpg" > "$tmpfile"
    neofetch --source "$tmpfile"
fi

rm "$tmpfile" "$tmpfile.jpg"

[ "$kitty_imagemagick_warn" = "true" ] && echo "WARN: imagemagick is required for kitty image backend"
