# Build a deb artifact on commit

name: CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build iOS deb
      run: make iosdeb
    - name: Build amd64 deb
      run: make amd64deb

    - name: Upload iphoneos-arm deb as artifact
      uses: actions/upload-artifact@v2
      with:
        name: iphoneos-arm-deb
        path: com.propr.nekofetch*iphoneos-arm.deb
    - name: Upload amd64 deb as artifact
      uses: actions/upload-artifact@v2
      with:
        name: amd64-deb
        path: nekofetch*amd64.deb
