# Build a deb artifact on commit

name: CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get commit hash
      id: hash
      run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"

    - name: Build deb for iphoneos-arm
      uses: jiro4989/build-deb-action@v2
      with:
        package: nekofetch
        package_root: pkgroot
        maintainer: propr and bbaovanc
        version: 0.2dev2-git-${{ steps.hash.outputs.sha_short }}
        arch: 'iphoneos-arm'
        desc: 'neofetch with nekos'
    - name: Build deb for amd64
      uses: jiro4989/build-deb-action@v2
      with:
        package: nekofetch
        package_root: pkgroot
        maintainer: propr and bbaovanc
        version: 0.2dev2-git-${{ steps.hash.outputs.sha_short }}
        arch: 'amd64'
        desc: 'neofetch with nekos'

    - name: Upload iphoneos-arm deb as artifact
      uses: actions/upload-artifact@v2
      with:
        name: iphoneos-arm-deb
        path: nekofetch*iphoneos-arm.deb
    - name: Upload amd64 deb as artifact
      uses: actions/upload-artifact@v2
      with:
        name: amd64-deb
        path: nekofetch*amd64.deb
